name: Antd China Area Data Example
on: [ push ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: example
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Use Yarn
        run: npm install -g yarn
      - name: Install
        run: |
          yarn
          yarn lint
          yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: example
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
